//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinWebsite_Application.DB_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CabinWebsiteEntities : DbContext
    {
        public CabinWebsiteEntities()
            : base("name=CabinWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<message> messages { get; set; }
        public DbSet<newsboard> newsboards { get; set; }
        public DbSet<reservation> reservations { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<Version> Versions { get; set; }
    }
}
