//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinWebsite_Application.DB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public string ID { get; set; }
        public Nullable<int> VersionNumber { get; set; }
    }
}
